Add a Fulldome fisheye lens that can be used to create planetarium content
Cykyrios/Godot360 pull request #4
Opened 2024-06-21 20:33 UTC by guillaumeriousat

This adds a `Fulldome` lens type to the camera 3d that adapts the fisheye projection so that its output conforms to the fulldome format commonly used by planetariums (see https://www.imersa.org/fulldome-file-specifications for more details). 

Conversely, this resolves [this issue](https://github.com/Cykyrios/Godot360/issues/1).

2024-06-23 05:17 UTC, Cykyrios requested changes
Thank you again for you contribution! I only have a few code style comments, and will add that I think the comments you added are a bit unnecessary IMO.
Other than that this works just fine, and the FoV is even correct, which is not exactly the case for the other projections... I might need to have another look there.

2024-06-23 05:17 UTC, Cykyrios commented on src/camera360/camera360.gdshader
> +}
For consistency, if you could add an empty line after this (I "grouped" the functions by projection, so it makes sense fulldome goes with fisheye).

2024-06-23 05:17 UTC, Cykyrios commented on src/camera360/camera360.gdshader
> +	vec2 dezoomed = p*2.0;
Spacing: `p * 2.0`

2024-06-25 13:34 UTC, guillaumeriousat commented
I have made the two small style changes you have requested.

With regards to the comments, I must admit I'm very new at shaders and glsl and having these kind of comments would have helped me figure it out quicker.

I can remove them if you want though.

2024-06-26 05:52 UTC, Cykyrios commented
Thanks, about the comments, my view on them is they should only exist to explain specific, non-standard decisions or other weirdness in the code, and not to describe what we're doing in general. I do understand they can help when you're reading an unfamiliar language or codebase though (I'm definitely rather a beginner in GLSL as well and needed some time before I understood how the original code worked).
I will merge as is, and maybe remove the comments later on when I go through the entire thing again at some point in the future.
Thank you again!

2024-06-26 05:52 UTC, Cykyrios approved these changes

2024-06-26 05:53 UTC, merged